apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim0
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi