kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    service: postgresql-claim0
  name:  postgresql-claim0
  namespace: n8n
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      service: postgres-pv0
