apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv0
  labels:
    service: postgres-pv0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/local/postgres  